/**
 */
package com.rm2pt.req.metamodel.req.provider;

import com.rm2pt.req.metamodel.req.util.ReqAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ReqItemProviderAdapterFactory extends ReqAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ReqItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.RequirementModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequirementModelItemProvider requirementModelItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.RequirementModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequirementModelAdapter() {
		if (requirementModelItemProvider == null) {
			requirementModelItemProvider = new RequirementModelItemProvider(this);
		}

		return requirementModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Interaction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InteractionItemProvider interactionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Interaction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInteractionAdapter() {
		if (interactionItemProvider == null) {
			interactionItemProvider = new InteractionItemProvider(this);
		}

		return interactionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Message} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageItemProvider messageItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Message}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMessageAdapter() {
		if (messageItemProvider == null) {
			messageItemProvider = new MessageItemProvider(this);
		}

		return messageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CallMessage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallMessageItemProvider callMessageItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CallMessage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallMessageAdapter() {
		if (callMessageItemProvider == null) {
			callMessageItemProvider = new CallMessageItemProvider(this);
		}

		return callMessageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ReturnMessage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnMessageItemProvider returnMessageItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ReturnMessage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnMessageAdapter() {
		if (returnMessageItemProvider == null) {
			returnMessageItemProvider = new ReturnMessageItemProvider(this);
		}

		return returnMessageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Execution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExecutionItemProvider executionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Execution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExecutionAdapter() {
		if (executionItemProvider == null) {
			executionItemProvider = new ExecutionItemProvider(this);
		}

		return executionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CombinedFragment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CombinedFragmentItemProvider combinedFragmentItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CombinedFragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCombinedFragmentAdapter() {
		if (combinedFragmentItemProvider == null) {
			combinedFragmentItemProvider = new CombinedFragmentItemProvider(this);
		}

		return combinedFragmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Operand} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperandItemProvider operandItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Operand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperandAdapter() {
		if (operandItemProvider == null) {
			operandItemProvider = new OperandItemProvider(this);
		}

		return operandItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.AbstractEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AbstractEndItemProvider abstractEndItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.AbstractEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAbstractEndAdapter() {
		if (abstractEndItemProvider == null) {
			abstractEndItemProvider = new AbstractEndItemProvider(this);
		}

		return abstractEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.MixEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MixEndItemProvider mixEndItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.MixEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMixEndAdapter() {
		if (mixEndItemProvider == null) {
			mixEndItemProvider = new MixEndItemProvider(this);
		}

		return mixEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.MixOpAndCFEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MixOpAndCFEndItemProvider mixOpAndCFEndItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.MixOpAndCFEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMixOpAndCFEndAdapter() {
		if (mixOpAndCFEndItemProvider == null) {
			mixOpAndCFEndItemProvider = new MixOpAndCFEndItemProvider(this);
		}

		return mixOpAndCFEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.MessageEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageEndItemProvider messageEndItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.MessageEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMessageEndAdapter() {
		if (messageEndItemProvider == null) {
			messageEndItemProvider = new MessageEndItemProvider(this);
		}

		return messageEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.MultiEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiEndItemProvider multiEndItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.MultiEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiEndAdapter() {
		if (multiEndItemProvider == null) {
			multiEndItemProvider = new MultiEndItemProvider(this);
		}

		return multiEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ExecutionEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExecutionEndItemProvider executionEndItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ExecutionEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExecutionEndAdapter() {
		if (executionEndItemProvider == null) {
			executionEndItemProvider = new ExecutionEndItemProvider(this);
		}

		return executionEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CombinedFragmentEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CombinedFragmentEndItemProvider combinedFragmentEndItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CombinedFragmentEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCombinedFragmentEndAdapter() {
		if (combinedFragmentEndItemProvider == null) {
			combinedFragmentEndItemProvider = new CombinedFragmentEndItemProvider(this);
		}

		return combinedFragmentEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.OperandEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperandEndItemProvider operandEndItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.OperandEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperandEndAdapter() {
		if (operandEndItemProvider == null) {
			operandEndItemProvider = new OperandEndItemProvider(this);
		}

		return operandEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.DomainModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainModelItemProvider domainModelItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.DomainModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainModelAdapter() {
		if (domainModelItemProvider == null) {
			domainModelItemProvider = new DomainModelItemProvider(this);
		}

		return domainModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.UseCaseModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UseCaseModelItemProvider useCaseModelItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.UseCaseModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUseCaseModelAdapter() {
		if (useCaseModelItemProvider == null) {
			useCaseModelItemProvider = new UseCaseModelItemProvider(this);
		}

		return useCaseModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Actor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActorItemProvider actorItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Actor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActorAdapter() {
		if (actorItemProvider == null) {
			actorItemProvider = new ActorItemProvider(this);
		}

		return actorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.UC} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UCItemProvider ucItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.UC}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUCAdapter() {
		if (ucItemProvider == null) {
			ucItemProvider = new UCItemProvider(this);
		}

		return ucItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Service} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceItemProvider serviceItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Service}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAdapter() {
		if (serviceItemProvider == null) {
			serviceItemProvider = new ServiceItemProvider(this);
		}

		return serviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Participant} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParticipantItemProvider participantItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Participant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParticipantAdapter() {
		if (participantItemProvider == null) {
			participantItemProvider = new ParticipantItemProvider(this);
		}

		return participantItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Workflow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkflowItemProvider workflowItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Workflow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkflowAdapter() {
		if (workflowItemProvider == null) {
			workflowItemProvider = new WorkflowItemProvider(this);
		}

		return workflowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Partition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PartitionItemProvider partitionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Partition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPartitionAdapter() {
		if (partitionItemProvider == null) {
			partitionItemProvider = new PartitionItemProvider(this);
		}

		return partitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.WorkflowExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkflowExpItemProvider workflowExpItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.WorkflowExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkflowExpAdapter() {
		if (workflowExpItemProvider == null) {
			workflowExpItemProvider = new WorkflowExpItemProvider(this);
		}

		return workflowExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.PartitionAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PartitionActionItemProvider partitionActionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.PartitionAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPartitionActionAdapter() {
		if (partitionActionItemProvider == null) {
			partitionActionItemProvider = new PartitionActionItemProvider(this);
		}

		return partitionActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.JoinExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoinExpItemProvider joinExpItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.JoinExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoinExpAdapter() {
		if (joinExpItemProvider == null) {
			joinExpItemProvider = new JoinExpItemProvider(this);
		}

		return joinExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ActivityFinal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivityFinalItemProvider activityFinalItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ActivityFinal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActivityFinalAdapter() {
		if (activityFinalItemProvider == null) {
			activityFinalItemProvider = new ActivityFinalItemProvider(this);
		}

		return activityFinalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.InitalNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InitalNodeItemProvider initalNodeItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.InitalNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInitalNodeAdapter() {
		if (initalNodeItemProvider == null) {
			initalNodeItemProvider = new InitalNodeItemProvider(this);
		}

		return initalNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ForkNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForkNodeItemProvider forkNodeItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ForkNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForkNodeAdapter() {
		if (forkNodeItemProvider == null) {
			forkNodeItemProvider = new ForkNodeItemProvider(this);
		}

		return forkNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.JoinNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoinNodeItemProvider joinNodeItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.JoinNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoinNodeAdapter() {
		if (joinNodeItemProvider == null) {
			joinNodeItemProvider = new JoinNodeItemProvider(this);
		}

		return joinNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ComplexOpeartion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComplexOpeartionItemProvider complexOpeartionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ComplexOpeartion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComplexOpeartionAdapter() {
		if (complexOpeartionItemProvider == null) {
			complexOpeartionItemProvider = new ComplexOpeartionItemProvider(this);
		}

		return complexOpeartionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.SimpleOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SimpleOperationItemProvider simpleOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.SimpleOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSimpleOperationAdapter() {
		if (simpleOperationItemProvider == null) {
			simpleOperationItemProvider = new SimpleOperationItemProvider(this);
		}

		return simpleOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.LoopExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoopExpItemProvider loopExpItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.LoopExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoopExpAdapter() {
		if (loopExpItemProvider == null) {
			loopExpItemProvider = new LoopExpItemProvider(this);
		}

		return loopExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.SwitchExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwitchExpItemProvider switchExpItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.SwitchExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwitchExpAdapter() {
		if (switchExpItemProvider == null) {
			switchExpItemProvider = new SwitchExpItemProvider(this);
		}

		return switchExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.SwitchCase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwitchCaseItemProvider switchCaseItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.SwitchCase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwitchCaseAdapter() {
		if (switchCaseItemProvider == null) {
			switchCaseItemProvider = new SwitchCaseItemProvider(this);
		}

		return switchCaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.SwitchDefault} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwitchDefaultItemProvider switchDefaultItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.SwitchDefault}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwitchDefaultAdapter() {
		if (switchDefaultItemProvider == null) {
			switchDefaultItemProvider = new SwitchDefaultItemProvider(this);
		}

		return switchDefaultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Operation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationItemProvider operationItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAdapter() {
		if (operationItemProvider == null) {
			operationItemProvider = new OperationItemProvider(this);
		}

		return operationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Entity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityItemProvider entityItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Entity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAdapter() {
		if (entityItemProvider == null) {
			entityItemProvider = new EntityItemProvider(this);
		}

		return entityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Attribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeItemProvider attributeItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Attribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeAdapter() {
		if (attributeItemProvider == null) {
			attributeItemProvider = new AttributeItemProvider(this);
		}

		return attributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Reference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceItemProvider referenceItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Reference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceAdapter() {
		if (referenceItemProvider == null) {
			referenceItemProvider = new ReferenceItemProvider(this);
		}

		return referenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.TypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeCSItemProvider typeCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.TypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeCSAdapter() {
		if (typeCSItemProvider == null) {
			typeCSItemProvider = new TypeCSItemProvider(this);
		}

		return typeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Invariance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InvarianceItemProvider invarianceItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Invariance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInvarianceAdapter() {
		if (invarianceItemProvider == null) {
			invarianceItemProvider = new InvarianceItemProvider(this);
		}

		return invarianceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.EntityType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityTypeItemProvider entityTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.EntityType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityTypeAdapter() {
		if (entityTypeItemProvider == null) {
			entityTypeItemProvider = new EntityTypeItemProvider(this);
		}

		return entityTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.EnumEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumEntityItemProvider enumEntityItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.EnumEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumEntityAdapter() {
		if (enumEntityItemProvider == null) {
			enumEntityItemProvider = new EnumEntityItemProvider(this);
		}

		return enumEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.EnumItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumItemItemProvider enumItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.EnumItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumItemAdapter() {
		if (enumItemItemProvider == null) {
			enumItemItemProvider = new EnumItemItemProvider(this);
		}

		return enumItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Contract} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContractItemProvider contractItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Contract}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContractAdapter() {
		if (contractItemProvider == null) {
			contractItemProvider = new ContractItemProvider(this);
		}

		return contractItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Definition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefinitionItemProvider definitionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Definition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefinitionAdapter() {
		if (definitionItemProvider == null) {
			definitionItemProvider = new DefinitionItemProvider(this);
		}

		return definitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Precondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PreconditionItemProvider preconditionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Precondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPreconditionAdapter() {
		if (preconditionItemProvider == null) {
			preconditionItemProvider = new PreconditionItemProvider(this);
		}

		return preconditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.Postcondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostconditionItemProvider postconditionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.Postcondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostconditionAdapter() {
		if (postconditionItemProvider == null) {
			postconditionItemProvider = new PostconditionItemProvider(this);
		}

		return postconditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.OCLExpressionCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OCLExpressionCSItemProvider oclExpressionCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.OCLExpressionCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOCLExpressionCSAdapter() {
		if (oclExpressionCSItemProvider == null) {
			oclExpressionCSItemProvider = new OCLExpressionCSItemProvider(this);
		}

		return oclExpressionCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.NestedExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NestedExpCSItemProvider nestedExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.NestedExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNestedExpCSAdapter() {
		if (nestedExpCSItemProvider == null) {
			nestedExpCSItemProvider = new NestedExpCSItemProvider(this);
		}

		return nestedExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.LogicFormulaExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicFormulaExpCSItemProvider logicFormulaExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.LogicFormulaExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicFormulaExpCSAdapter() {
		if (logicFormulaExpCSItemProvider == null) {
			logicFormulaExpCSItemProvider = new LogicFormulaExpCSItemProvider(this);
		}

		return logicFormulaExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.AtomicExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtomicExpressionItemProvider atomicExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.AtomicExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtomicExpressionAdapter() {
		if (atomicExpressionItemProvider == null) {
			atomicExpressionItemProvider = new AtomicExpressionItemProvider(this);
		}

		return atomicExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.LeftSubAtomicExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LeftSubAtomicExpressionItemProvider leftSubAtomicExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.LeftSubAtomicExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLeftSubAtomicExpressionAdapter() {
		if (leftSubAtomicExpressionItemProvider == null) {
			leftSubAtomicExpressionItemProvider = new LeftSubAtomicExpressionItemProvider(this);
		}

		return leftSubAtomicExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.RightSubAtomicExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RightSubAtomicExpressionItemProvider rightSubAtomicExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.RightSubAtomicExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRightSubAtomicExpressionAdapter() {
		if (rightSubAtomicExpressionItemProvider == null) {
			rightSubAtomicExpressionItemProvider = new RightSubAtomicExpressionItemProvider(this);
		}

		return rightSubAtomicExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallExpCSItemProvider callExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallExpCSAdapter() {
		if (callExpCSItemProvider == null) {
			callExpCSItemProvider = new CallExpCSItemProvider(this);
		}

		return callExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.LoopExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoopExpCSItemProvider loopExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.LoopExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoopExpCSAdapter() {
		if (loopExpCSItemProvider == null) {
			loopExpCSItemProvider = new LoopExpCSItemProvider(this);
		}

		return loopExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.IteratorExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IteratorExpCSItemProvider iteratorExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.IteratorExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIteratorExpCSAdapter() {
		if (iteratorExpCSItemProvider == null) {
			iteratorExpCSItemProvider = new IteratorExpCSItemProvider(this);
		}

		return iteratorExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.EntityAttributeName} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityAttributeNameItemProvider entityAttributeNameItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.EntityAttributeName}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAttributeNameAdapter() {
		if (entityAttributeNameItemProvider == null) {
			entityAttributeNameItemProvider = new EntityAttributeNameItemProvider(this);
		}

		return entityAttributeNameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ArgumentsCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArgumentsCSItemProvider argumentsCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ArgumentsCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArgumentsCSAdapter() {
		if (argumentsCSItemProvider == null) {
			argumentsCSItemProvider = new ArgumentsCSItemProvider(this);
		}

		return argumentsCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.FeatureCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureCallExpCSItemProvider featureCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.FeatureCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureCallExpCSAdapter() {
		if (featureCallExpCSItemProvider == null) {
			featureCallExpCSItemProvider = new FeatureCallExpCSItemProvider(this);
		}

		return featureCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.StandardNavigationCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardNavigationCallExpCSItemProvider standardNavigationCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.StandardNavigationCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardNavigationCallExpCSAdapter() {
		if (standardNavigationCallExpCSItemProvider == null) {
			standardNavigationCallExpCSItemProvider = new StandardNavigationCallExpCSItemProvider(this);
		}

		return standardNavigationCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.StandardOperationExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardOperationExpCSItemProvider standardOperationExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.StandardOperationExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardOperationExpCSAdapter() {
		if (standardOperationExpCSItemProvider == null) {
			standardOperationExpCSItemProvider = new StandardOperationExpCSItemProvider(this);
		}

		return standardOperationExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.PredefineOp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PredefineOpItemProvider predefineOpItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.PredefineOp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPredefineOpAdapter() {
		if (predefineOpItemProvider == null) {
			predefineOpItemProvider = new PredefineOpItemProvider(this);
		}

		return predefineOpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.StandardNoneParameterOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardNoneParameterOperationItemProvider standardNoneParameterOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.StandardNoneParameterOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardNoneParameterOperationAdapter() {
		if (standardNoneParameterOperationItemProvider == null) {
			standardNoneParameterOperationItemProvider = new StandardNoneParameterOperationItemProvider(this);
		}

		return standardNoneParameterOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.StandardParameterOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardParameterOperationItemProvider standardParameterOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.StandardParameterOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardParameterOperationAdapter() {
		if (standardParameterOperationItemProvider == null) {
			standardParameterOperationItemProvider = new StandardParameterOperationItemProvider(this);
		}

		return standardParameterOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.StandardCollectionOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardCollectionOperationItemProvider standardCollectionOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.StandardCollectionOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardCollectionOperationAdapter() {
		if (standardCollectionOperationItemProvider == null) {
			standardCollectionOperationItemProvider = new StandardCollectionOperationItemProvider(this);
		}

		return standardCollectionOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.StandardDateOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardDateOperationItemProvider standardDateOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.StandardDateOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardDateOperationAdapter() {
		if (standardDateOperationItemProvider == null) {
			standardDateOperationItemProvider = new StandardDateOperationItemProvider(this);
		}

		return standardDateOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ClassiferCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassiferCallExpCSItemProvider classiferCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ClassiferCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassiferCallExpCSAdapter() {
		if (classiferCallExpCSItemProvider == null) {
			classiferCallExpCSItemProvider = new ClassiferCallExpCSItemProvider(this);
		}

		return classiferCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.PropertyCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyCallExpCSItemProvider propertyCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.PropertyCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyCallExpCSAdapter() {
		if (propertyCallExpCSItemProvider == null) {
			propertyCallExpCSItemProvider = new PropertyCallExpCSItemProvider(this);
		}

		return propertyCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.OperationCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationCallExpCSItemProvider operationCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.OperationCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationCallExpCSAdapter() {
		if (operationCallExpCSItemProvider == null) {
			operationCallExpCSItemProvider = new OperationCallExpCSItemProvider(this);
		}

		return operationCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.OperationParameters} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationParametersItemProvider operationParametersItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.OperationParameters}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationParametersAdapter() {
		if (operationParametersItemProvider == null) {
			operationParametersItemProvider = new OperationParametersItemProvider(this);
		}

		return operationParametersItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.VariableExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableExpCSItemProvider variableExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.VariableExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableExpCSAdapter() {
		if (variableExpCSItemProvider == null) {
			variableExpCSItemProvider = new VariableExpCSItemProvider(this);
		}

		return variableExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.IfExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IfExpCSItemProvider ifExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.IfExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIfExpCSAdapter() {
		if (ifExpCSItemProvider == null) {
			ifExpCSItemProvider = new IfExpCSItemProvider(this);
		}

		return ifExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.LetExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LetExpCSItemProvider letExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.LetExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLetExpCSAdapter() {
		if (letExpCSItemProvider == null) {
			letExpCSItemProvider = new LetExpCSItemProvider(this);
		}

		return letExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.VariableDeclarationCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableDeclarationCSItemProvider variableDeclarationCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.VariableDeclarationCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableDeclarationCSAdapter() {
		if (variableDeclarationCSItemProvider == null) {
			variableDeclarationCSItemProvider = new VariableDeclarationCSItemProvider(this);
		}

		return variableDeclarationCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.LiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LiteralExpCSItemProvider literalExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.LiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLiteralExpCSAdapter() {
		if (literalExpCSItemProvider == null) {
			literalExpCSItemProvider = new LiteralExpCSItemProvider(this);
		}

		return literalExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.EnumLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumLiteralExpCSItemProvider enumLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.EnumLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumLiteralExpCSAdapter() {
		if (enumLiteralExpCSItemProvider == null) {
			enumLiteralExpCSItemProvider = new EnumLiteralExpCSItemProvider(this);
		}

		return enumLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.TupleLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TupleLiteralExpCSItemProvider tupleLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.TupleLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTupleLiteralExpCSAdapter() {
		if (tupleLiteralExpCSItemProvider == null) {
			tupleLiteralExpCSItemProvider = new TupleLiteralExpCSItemProvider(this);
		}

		return tupleLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.TupleTypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TupleTypeCSItemProvider tupleTypeCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.TupleTypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTupleTypeCSAdapter() {
		if (tupleTypeCSItemProvider == null) {
			tupleTypeCSItemProvider = new TupleTypeCSItemProvider(this);
		}

		return tupleTypeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CollectionTypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionTypeCSItemProvider collectionTypeCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CollectionTypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionTypeCSAdapter() {
		if (collectionTypeCSItemProvider == null) {
			collectionTypeCSItemProvider = new CollectionTypeCSItemProvider(this);
		}

		return collectionTypeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CollectionLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionLiteralExpCSItemProvider collectionLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CollectionLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionLiteralExpCSAdapter() {
		if (collectionLiteralExpCSItemProvider == null) {
			collectionLiteralExpCSItemProvider = new CollectionLiteralExpCSItemProvider(this);
		}

		return collectionLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CollectionLiteralPartCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionLiteralPartCSItemProvider collectionLiteralPartCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CollectionLiteralPartCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionLiteralPartCSAdapter() {
		if (collectionLiteralPartCSItemProvider == null) {
			collectionLiteralPartCSItemProvider = new CollectionLiteralPartCSItemProvider(this);
		}

		return collectionLiteralPartCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CollectionRangeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionRangeCSItemProvider collectionRangeCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CollectionRangeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionRangeCSAdapter() {
		if (collectionRangeCSItemProvider == null) {
			collectionRangeCSItemProvider = new CollectionRangeCSItemProvider(this);
		}

		return collectionRangeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CollectionItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionItemItemProvider collectionItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CollectionItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionItemAdapter() {
		if (collectionItemItemProvider == null) {
			collectionItemItemProvider = new CollectionItemItemProvider(this);
		}

		return collectionItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.PrimitiveLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveLiteralExpCSItemProvider primitiveLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.PrimitiveLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveLiteralExpCSAdapter() {
		if (primitiveLiteralExpCSItemProvider == null) {
			primitiveLiteralExpCSItemProvider = new PrimitiveLiteralExpCSItemProvider(this);
		}

		return primitiveLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.NumberLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumberLiteralExpCSItemProvider numberLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.NumberLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumberLiteralExpCSAdapter() {
		if (numberLiteralExpCSItemProvider == null) {
			numberLiteralExpCSItemProvider = new NumberLiteralExpCSItemProvider(this);
		}

		return numberLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.BooleanLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanLiteralExpCSItemProvider booleanLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.BooleanLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanLiteralExpCSAdapter() {
		if (booleanLiteralExpCSItemProvider == null) {
			booleanLiteralExpCSItemProvider = new BooleanLiteralExpCSItemProvider(this);
		}

		return booleanLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.StringLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringLiteralExpCSItemProvider stringLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.StringLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringLiteralExpCSAdapter() {
		if (stringLiteralExpCSItemProvider == null) {
			stringLiteralExpCSItemProvider = new StringLiteralExpCSItemProvider(this);
		}

		return stringLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.NullLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NullLiteralExpCSItemProvider nullLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.NullLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNullLiteralExpCSAdapter() {
		if (nullLiteralExpCSItemProvider == null) {
			nullLiteralExpCSItemProvider = new NullLiteralExpCSItemProvider(this);
		}

		return nullLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.InvalidLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InvalidLiteralExpCSItemProvider invalidLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.InvalidLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInvalidLiteralExpCSAdapter() {
		if (invalidLiteralExpCSItemProvider == null) {
			invalidLiteralExpCSItemProvider = new InvalidLiteralExpCSItemProvider(this);
		}

		return invalidLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ReservedKeywordCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReservedKeywordCSItemProvider reservedKeywordCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ReservedKeywordCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReservedKeywordCSAdapter() {
		if (reservedKeywordCSItemProvider == null) {
			reservedKeywordCSItemProvider = new ReservedKeywordCSItemProvider(this);
		}

		return reservedKeywordCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.CollectionTypeIdentifierCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionTypeIdentifierCSItemProvider collectionTypeIdentifierCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.CollectionTypeIdentifierCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionTypeIdentifierCSAdapter() {
		if (collectionTypeIdentifierCSItemProvider == null) {
			collectionTypeIdentifierCSItemProvider = new CollectionTypeIdentifierCSItemProvider(this);
		}

		return collectionTypeIdentifierCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.PrimitiveTypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveTypeCSItemProvider primitiveTypeCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.PrimitiveTypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveTypeCSAdapter() {
		if (primitiveTypeCSItemProvider == null) {
			primitiveTypeCSItemProvider = new PrimitiveTypeCSItemProvider(this);
		}

		return primitiveTypeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.OclTypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OclTypeCSItemProvider oclTypeCSItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.OclTypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOclTypeCSAdapter() {
		if (oclTypeCSItemProvider == null) {
			oclTypeCSItemProvider = new OclTypeCSItemProvider(this);
		}

		return oclTypeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.UseCaseContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UseCaseContextItemProvider useCaseContextItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.UseCaseContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUseCaseContextAdapter() {
		if (useCaseContextItemProvider == null) {
			useCaseContextItemProvider = new UseCaseContextItemProvider(this);
		}

		return useCaseContextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.EntityContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityContextItemProvider entityContextItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.EntityContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityContextAdapter() {
		if (entityContextItemProvider == null) {
			entityContextItemProvider = new EntityContextItemProvider(this);
		}

		return entityContextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.SystemInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemInterfaceItemProvider systemInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.SystemInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemInterfaceAdapter() {
		if (systemInterfaceItemProvider == null) {
			systemInterfaceItemProvider = new SystemInterfaceItemProvider(this);
		}

		return systemInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ReceiveInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReceiveInterfaceItemProvider receiveInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ReceiveInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReceiveInterfaceAdapter() {
		if (receiveInterfaceItemProvider == null) {
			receiveInterfaceItemProvider = new ReceiveInterfaceItemProvider(this);
		}

		return receiveInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.ProvideInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProvideInterfaceItemProvider provideInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.ProvideInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProvideInterfaceAdapter() {
		if (provideInterfaceItemProvider == null) {
			provideInterfaceItemProvider = new ProvideInterfaceItemProvider(this);
		}

		return provideInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.UserInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UserInterfaceItemProvider userInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.UserInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUserInterfaceAdapter() {
		if (userInterfaceItemProvider == null) {
			userInterfaceItemProvider = new UserInterfaceItemProvider(this);
		}

		return userInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.rm2pt.req.metamodel.req.NF} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NFItemProvider nfItemProvider;

	/**
	 * This creates an adapter for a {@link com.rm2pt.req.metamodel.req.NF}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNFAdapter() {
		if (nfItemProvider == null) {
			nfItemProvider = new NFItemProvider(this);
		}

		return nfItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (requirementModelItemProvider != null)
			requirementModelItemProvider.dispose();
		if (interactionItemProvider != null)
			interactionItemProvider.dispose();
		if (messageItemProvider != null)
			messageItemProvider.dispose();
		if (callMessageItemProvider != null)
			callMessageItemProvider.dispose();
		if (returnMessageItemProvider != null)
			returnMessageItemProvider.dispose();
		if (executionItemProvider != null)
			executionItemProvider.dispose();
		if (combinedFragmentItemProvider != null)
			combinedFragmentItemProvider.dispose();
		if (operandItemProvider != null)
			operandItemProvider.dispose();
		if (abstractEndItemProvider != null)
			abstractEndItemProvider.dispose();
		if (mixEndItemProvider != null)
			mixEndItemProvider.dispose();
		if (mixOpAndCFEndItemProvider != null)
			mixOpAndCFEndItemProvider.dispose();
		if (messageEndItemProvider != null)
			messageEndItemProvider.dispose();
		if (multiEndItemProvider != null)
			multiEndItemProvider.dispose();
		if (executionEndItemProvider != null)
			executionEndItemProvider.dispose();
		if (combinedFragmentEndItemProvider != null)
			combinedFragmentEndItemProvider.dispose();
		if (operandEndItemProvider != null)
			operandEndItemProvider.dispose();
		if (domainModelItemProvider != null)
			domainModelItemProvider.dispose();
		if (useCaseModelItemProvider != null)
			useCaseModelItemProvider.dispose();
		if (actorItemProvider != null)
			actorItemProvider.dispose();
		if (ucItemProvider != null)
			ucItemProvider.dispose();
		if (serviceItemProvider != null)
			serviceItemProvider.dispose();
		if (participantItemProvider != null)
			participantItemProvider.dispose();
		if (workflowItemProvider != null)
			workflowItemProvider.dispose();
		if (partitionItemProvider != null)
			partitionItemProvider.dispose();
		if (workflowExpItemProvider != null)
			workflowExpItemProvider.dispose();
		if (partitionActionItemProvider != null)
			partitionActionItemProvider.dispose();
		if (joinExpItemProvider != null)
			joinExpItemProvider.dispose();
		if (activityFinalItemProvider != null)
			activityFinalItemProvider.dispose();
		if (initalNodeItemProvider != null)
			initalNodeItemProvider.dispose();
		if (forkNodeItemProvider != null)
			forkNodeItemProvider.dispose();
		if (joinNodeItemProvider != null)
			joinNodeItemProvider.dispose();
		if (complexOpeartionItemProvider != null)
			complexOpeartionItemProvider.dispose();
		if (simpleOperationItemProvider != null)
			simpleOperationItemProvider.dispose();
		if (loopExpItemProvider != null)
			loopExpItemProvider.dispose();
		if (switchExpItemProvider != null)
			switchExpItemProvider.dispose();
		if (switchCaseItemProvider != null)
			switchCaseItemProvider.dispose();
		if (switchDefaultItemProvider != null)
			switchDefaultItemProvider.dispose();
		if (operationItemProvider != null)
			operationItemProvider.dispose();
		if (parameterItemProvider != null)
			parameterItemProvider.dispose();
		if (entityItemProvider != null)
			entityItemProvider.dispose();
		if (attributeItemProvider != null)
			attributeItemProvider.dispose();
		if (referenceItemProvider != null)
			referenceItemProvider.dispose();
		if (typeCSItemProvider != null)
			typeCSItemProvider.dispose();
		if (invarianceItemProvider != null)
			invarianceItemProvider.dispose();
		if (entityTypeItemProvider != null)
			entityTypeItemProvider.dispose();
		if (enumEntityItemProvider != null)
			enumEntityItemProvider.dispose();
		if (enumItemItemProvider != null)
			enumItemItemProvider.dispose();
		if (contractItemProvider != null)
			contractItemProvider.dispose();
		if (definitionItemProvider != null)
			definitionItemProvider.dispose();
		if (preconditionItemProvider != null)
			preconditionItemProvider.dispose();
		if (postconditionItemProvider != null)
			postconditionItemProvider.dispose();
		if (oclExpressionCSItemProvider != null)
			oclExpressionCSItemProvider.dispose();
		if (nestedExpCSItemProvider != null)
			nestedExpCSItemProvider.dispose();
		if (logicFormulaExpCSItemProvider != null)
			logicFormulaExpCSItemProvider.dispose();
		if (atomicExpressionItemProvider != null)
			atomicExpressionItemProvider.dispose();
		if (leftSubAtomicExpressionItemProvider != null)
			leftSubAtomicExpressionItemProvider.dispose();
		if (rightSubAtomicExpressionItemProvider != null)
			rightSubAtomicExpressionItemProvider.dispose();
		if (callExpCSItemProvider != null)
			callExpCSItemProvider.dispose();
		if (loopExpCSItemProvider != null)
			loopExpCSItemProvider.dispose();
		if (iteratorExpCSItemProvider != null)
			iteratorExpCSItemProvider.dispose();
		if (entityAttributeNameItemProvider != null)
			entityAttributeNameItemProvider.dispose();
		if (argumentsCSItemProvider != null)
			argumentsCSItemProvider.dispose();
		if (featureCallExpCSItemProvider != null)
			featureCallExpCSItemProvider.dispose();
		if (standardNavigationCallExpCSItemProvider != null)
			standardNavigationCallExpCSItemProvider.dispose();
		if (standardOperationExpCSItemProvider != null)
			standardOperationExpCSItemProvider.dispose();
		if (predefineOpItemProvider != null)
			predefineOpItemProvider.dispose();
		if (standardNoneParameterOperationItemProvider != null)
			standardNoneParameterOperationItemProvider.dispose();
		if (standardParameterOperationItemProvider != null)
			standardParameterOperationItemProvider.dispose();
		if (standardCollectionOperationItemProvider != null)
			standardCollectionOperationItemProvider.dispose();
		if (standardDateOperationItemProvider != null)
			standardDateOperationItemProvider.dispose();
		if (classiferCallExpCSItemProvider != null)
			classiferCallExpCSItemProvider.dispose();
		if (propertyCallExpCSItemProvider != null)
			propertyCallExpCSItemProvider.dispose();
		if (operationCallExpCSItemProvider != null)
			operationCallExpCSItemProvider.dispose();
		if (operationParametersItemProvider != null)
			operationParametersItemProvider.dispose();
		if (variableExpCSItemProvider != null)
			variableExpCSItemProvider.dispose();
		if (ifExpCSItemProvider != null)
			ifExpCSItemProvider.dispose();
		if (letExpCSItemProvider != null)
			letExpCSItemProvider.dispose();
		if (variableDeclarationCSItemProvider != null)
			variableDeclarationCSItemProvider.dispose();
		if (literalExpCSItemProvider != null)
			literalExpCSItemProvider.dispose();
		if (enumLiteralExpCSItemProvider != null)
			enumLiteralExpCSItemProvider.dispose();
		if (tupleLiteralExpCSItemProvider != null)
			tupleLiteralExpCSItemProvider.dispose();
		if (tupleTypeCSItemProvider != null)
			tupleTypeCSItemProvider.dispose();
		if (collectionTypeCSItemProvider != null)
			collectionTypeCSItemProvider.dispose();
		if (collectionLiteralExpCSItemProvider != null)
			collectionLiteralExpCSItemProvider.dispose();
		if (collectionLiteralPartCSItemProvider != null)
			collectionLiteralPartCSItemProvider.dispose();
		if (collectionRangeCSItemProvider != null)
			collectionRangeCSItemProvider.dispose();
		if (collectionItemItemProvider != null)
			collectionItemItemProvider.dispose();
		if (primitiveLiteralExpCSItemProvider != null)
			primitiveLiteralExpCSItemProvider.dispose();
		if (numberLiteralExpCSItemProvider != null)
			numberLiteralExpCSItemProvider.dispose();
		if (booleanLiteralExpCSItemProvider != null)
			booleanLiteralExpCSItemProvider.dispose();
		if (stringLiteralExpCSItemProvider != null)
			stringLiteralExpCSItemProvider.dispose();
		if (nullLiteralExpCSItemProvider != null)
			nullLiteralExpCSItemProvider.dispose();
		if (invalidLiteralExpCSItemProvider != null)
			invalidLiteralExpCSItemProvider.dispose();
		if (reservedKeywordCSItemProvider != null)
			reservedKeywordCSItemProvider.dispose();
		if (collectionTypeIdentifierCSItemProvider != null)
			collectionTypeIdentifierCSItemProvider.dispose();
		if (primitiveTypeCSItemProvider != null)
			primitiveTypeCSItemProvider.dispose();
		if (oclTypeCSItemProvider != null)
			oclTypeCSItemProvider.dispose();
		if (useCaseContextItemProvider != null)
			useCaseContextItemProvider.dispose();
		if (entityContextItemProvider != null)
			entityContextItemProvider.dispose();
		if (systemInterfaceItemProvider != null)
			systemInterfaceItemProvider.dispose();
		if (receiveInterfaceItemProvider != null)
			receiveInterfaceItemProvider.dispose();
		if (provideInterfaceItemProvider != null)
			provideInterfaceItemProvider.dispose();
		if (userInterfaceItemProvider != null)
			userInterfaceItemProvider.dispose();
		if (nfItemProvider != null)
			nfItemProvider.dispose();
	}

}
